name: delete all resources

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'experimental'

permissions:
  id-token: write
  contents: read
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # Checkout code
    - uses: actions/checkout@main

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.53.0
        inlineScript: |
          az deployment group create --mode complete --resource-group ${{ vars.RESOURCE_GROUP_NAME }}-rg -template $GITHUB_WORKSPACE/bicep/delete.bicep
