name: deploy-rg-and-resources

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - experimental

permissions:
  id-token: write
  contents: read
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # Checkout code
    - uses: actions/checkout@main

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # - name: 'Deploy infrastructue with powershell'
    #   uses: azure/powershell@v1
    #   with:
    #     inlineScript: |
    #       Get-AzVM -ResourceGroupName "cloud-shell-storage-westeurope"
    #     azPSVersion: '3.1.0'
    


    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.53.0
        inlineScript: |
          az bicep install
          az bicep version
          az deployment sub create --location norwayeast --template-file $GITHUB_WORKSPACE/bicep/main.bicep --parameters $GITHUB_WORKSPACE/bicep/main.bicepparam

    # - name: deploy
    #   uses: azure/arm-deploy@v1
    #   with:
    #     scope: subscription
    #     region: 'norwayeast'
    #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  
    #     template: ./bicep/main.bicep
    #     parameters: ./bicep/main.bicepparams
    #     failOnStdErr: false
