name: deploy-rg-and-resources

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - experimental

permissions:
  id-token: write
  contents: read
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # Checkout code
    - uses: actions/checkout@main

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        region: 'norwayeast'
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  
        template: ./bicep/main.bicep
        parameters: ./bicep/main.bicepparams
        failOnStdErr: false
