name: deploy-rg-and-resources

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - experimental

permissions:
  id-token: write
  contents: read
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # Checkout code
    - uses: actions/checkout@main

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.53.0
        inlineScript: |
          export RGNAME='${{ vars.RESOURCE_GROUP_NAME }}'
          az deployment sub create --location norwayeast --parameters $GITHUB_WORKSPACE/bicep/main.bicepparam

    # - name: Azure CLI script
    #   uses: azure/CLI@v1
    #   with:
    #     azcliversion: 2.53.0
    #     inlineScript: |
    #       export RGNAME='${{ vars.RESOURCE_GROUP_NAME }}'

    # - name: deploy
    #   uses: azure/arm-deploy@v1
    #   with:
    #     scope: subscription
    #     region: 'norwayeast'
    #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #     template: ./bicep/main.bicep
    #     parameters: ./bicep/main.bicepparam
    #     failOnStdErr: false
