name: deploy-rg-and-resources

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - experimental

permissions:
  id-token: write
  contents: read
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: AZ cli login
        # Log into Azure
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Setup az resource group
        run: |
          az account show
          az group list
